# Generated by Django 3.2.9 on 2021-11-27 07:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('auth_custom', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.IntegerField(choices=[(1, 'Инвестор'), (2, 'Компания'), (3, 'Никто')], default=3),
        ),
    ]
