# Generated by Django 3.2.9 on 2021-11-27 07:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BusinessCenter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('region', models.IntegerField(choices=[(1, 'Аламалинский р-н'), (2, 'Бостандыкский р-н')])),
                ('address', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('address', models.CharField(max_length=70)),
                ('bin_iin', models.CharField(max_length=15)),
                ('iik', models.CharField(max_length=100)),
                ('bik', models.CharField(max_length=100)),
                ('bank_name', models.CharField(max_length=100)),
                ('activity', models.IntegerField(choices=[(1, 'Продажа проездных документов (билетов)'), (2, 'Создание IT стартапов')])),
                ('type', models.IntegerField(choices=[(1, 'ТОО'), (2, 'АО'), (3, 'ИП')])),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='CompanyWorker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('position', models.IntegerField(choices=[(1, 'Back-end программист'), (2, 'Front-end программист'), (3, 'Web - дизайнер')])),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='business.company')),
            ],
        ),
    ]
