# Generated by Django 3.2.9 on 2021-11-27 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='company',
            name='activity',
        ),
        migrations.AlterField(
            model_name='company',
            name='bin_iin',
            field=models.CharField(max_length=30),
        ),
        migrations.AlterField(
            model_name='company',
            name='type',
            field=models.IntegerField(choices=[(0, 'Выберите форму предпринимательства Вашей организации'), (1, 'ТОО'), (2, 'ИП'), (3, 'АО')]),
        ),
    ]
