# Generated by Django 3.2.9 on 2021-11-27 23:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('business', '0002_auto_20211127_2049'),
    ]

    operations = [
        migrations.AddField(
            model_name='company',
            name='is_init',
            field=models.BooleanField(default=False),
        ),
    ]
